### ISSUE TITLE
[ Busy_Box ] Is the VmCheker running properly

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/sde#10]
Hello, i just made some modifications to my homework ( still not complete ) and now VmChecker gives me 0.5 points.

I was just wondering if this is an issue with VmChecker or my homework

**Comment by ioanaculic** [comment]
Hello!

There is a problem in your homework at line 47. This is why most of the tests fail.

**Comment by RaduNicolaeEduard** [comment]
Hello, now that i see that the homework has been updated with different exit codes, i think that i will start from scratch.
Anyway Thank You ! :+1:

**Comment by ioanaculic** [comment]
The exit codes do not imply major changes, you simply have to replace the value 1 with a different value.
