### ISSUE TITLE
Testing homework 2 with github verify devoir

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#13]
Good morning ! Hi,omeone can explain to me how can i use the verify tests correctly? Maybe I' m wrong ... I tested all the commands that i wrote in the terminal with github tool,BUT just some tests are passed although in the code i have no errors , it isn't  much until now, BUT think I 'm going  to upload the archive  , hoping  that i'll receive some suggestions!

**Comment by ioanaculic** [comment]
Hello,

Please refer to #12

**Comment by AlexandruCristian2312** [comment]
I 've seen all the issues posted before , doesn't help me , i'll read again the homework! 
    Pe miercuri, 11 martie 2020, 12:06:12 EET, Ioana Culic <notifications@github.com> a scris:  
 
 
Hello,

Please refer to #12
