### ISSUE TITLE
[busybox] Return...?

### ISSUE THREAD

**Issue by alfredrogoveanu** [UPB-FILS/sde#15]
Hello,

I have a problem with the Returns, the tests for the invalid commands say that they **don't return -1** as well. Can you please check my code and if I am wrong, can I get a hint or a reference about how it should be done?

Many thanks!

**Comment by ioanaculic** [comment]
Hello,

First of all, when handling an invalid command, you are trying to return the value 1, not -1. 
Secondly, you need to make sure the application exits with the specified error code.

**Comment by alfredrogoveanu** [comment]
Thank you for the answer, I get it now and I modified, but still, the tests for the invalid commands print the error _Script does not return -1 when command is not correct._ despite setting either 1 or -1...

As for the -1, on the website, it specifies that it returns -1...:

> Pour toute autre commande ou pour un format différent, le script va afficher le message Invalid command et il **va retourner la valeur -1**.

Or did I miss something...?

Thank you!

**Comment by ioanaculic** [comment]
This means that after running the busybox.py file the result ($?) must be -1.

**Comment by alfredrogoveanu** [comment]
It prints 255 if I set -1.

![image](https://user-images.githubusercontent.com/47867913/76664331-a79afa80-658c-11ea-94fc-62296b439fbd.png)

**Comment by alexandruradovici** [comment]
bash will only print unsigned numbers, -1 is the same as 255.

**Comment by ioanaculic** [comment]
Indeed, this does not work as expected. At the moment the error checking tests do not work because of this. We will change the checker so errors are verified correctly. Please try to resubmit the homework in around 30 minutes.

We will also add in the homework text the error codes that you should see in the bash.

**Comment by alfredrogoveanu** [comment]
Sorry for the delay and many thanks! I tested and it's solved for the invalid tests. :+1: 
However, the cat tests, Vmchecker says they don't return 0, despite being set to 0.

Thank you!

**Comment by ioanaculic** [comment]
The cat_simple test runs the following command: `python3 busybox.py cat /dev/nasty`
I ran this on my computer and the result code is 236.

I guess there is some error when trying to read the files.
I noticed you do some changes to the filenames, this should not happen (line 90).
