### ISSUE TITLE
[mini-shell] questions related to parser

### ISSUE THREAD

**Issue by daniciucBianca** [UPB-FILS/sde#18]
-> the function 'parse_line' doesn't have a definition in the file cmd.c, it's non-existent, but it is called in main.c at line 81. What should be done in this situation?

-> in 'parser.h' what does OP_CONDITIONAL_ZERO and OP_CONDINTIONAL_NZERO mean? Sth with bool false and true? (???)

-> OP_DUMMY is unused, it will cause an warning, why is it unused  and what should be done with it? is it viewed here as a mannequin of sth or sth like that?

**Comment by alexandruradovici** [comment]
> -> the function 'parse_line' doesn't have a definition in the file cmd.c, it's non-existent, but it is called in main.c at line 81. What should be done in this situation?
The function is defined in the parser in parser.tab.c, you do not need it

> -> in 'parser.h' what does OP_CONDITIONAL_ZERO and OP_CONDINTIONAL_NZERO mean? Sth with bool false and true? (???)

Those are the possible operators in the command line:
OP_CONDITIONAL_ZERO is &&
OP_CONDINTIONAL_NZERO is ||

> -> OP_DUMMY is unused, it will cause an warning, why is it unused and what should be done with it? is it viewed here as a mannequin of sth or sth like that?
It has no use
