### ISSUE TITLE
I have the following error when I am trying to start the virtual machine. What should I do?

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/sde#2]
![1](https://user-images.githubusercontent.com/47796147/53046272-59eeb400-3498-11e9-98bf-a512596c32ae.PNG)

**Comment by alexandruradovici** [comment]
Please ask in English as some people might not understand Romanian.
The answer is here (point11):

FR - https://ocw.cs.pub.ro/courses/sde/teme/intrebari-frecvente_fr
RO - https://ocw.cs.pub.ro/courses/sde/teme/intrebari-frecvente

**Comment by alexandruradovici** [comment]
You may also enable VT-x in BIOS/UEFI.  Here are some articles on how to do that:

1. https://docs.fedoraproject.org/en-US/Fedora/13/html/Virtualization_Guide/sect-Virtualization-Troubleshooting-Enabling_Intel_VT_and_AMD_V_virtualization_hardware_extensions_in_BIOS.html
2. https://2nwiki.2n.cz/pages/viewpage.action?pageId=75202968
