### ISSUE TITLE
Buna ziua ,am o eroare la instalarea pachetului git! Imi da eroarea : Couldn't find any package !

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#2]

**Comment by RaduNicolaeEduard** [comment]
Am avut si eu aceași eroare, caută pe internet cum se foloseste comanda git, si o sa găsești o rezolvare.

Si sa scrii link-ul bine.
[https://github.com/upb-fils/sde](url)

**Comment by AlexandruCristian2312** [comment]
Multumesc mult! Eroarea era de la checker ,am folosit sudo uso update si am actualizat versiunea de checker!
