### ISSUE TITLE
Command does not return 0. And chmod, cp.

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/sde#20]
I have been trying for a while to order "cat" to make it work and I can't. I have that function to return the value 0 and the check doesn't see. I also tested manually with Pycharm (where you see the return value) and it still doesn't work.

In chmod to the one with ugo +/- rwx, does that persecution add to the ones you already have or a new permission code is formed?

For the "cp" order, on the premises, I go perfectly and the checker does not

**Comment by ZamfirAndreiPaul** [comment]
Here I test local my chmod and work...
![chmod1](https://user-images.githubusercontent.com/56279630/76698267-a57a8e00-66a9-11ea-9848-c8760cb8e794.png)
![chmod2](https://user-images.githubusercontent.com/56279630/76698268-a7445180-66a9-11ea-8a06-fba9638e28cf.png)

**Comment by ZamfirAndreiPaul** [comment]
Here I test local command "cat
![cat](https://user-images.githubusercontent.com/56279630/76698344-6ef14300-66aa-11ea-84bc-848d8763f60b.png)
"

**Comment by ZamfirAndreiPaul** [comment]
Here I test cp command 
![c1](https://user-images.githubusercontent.com/56279630/76698425-6fd6a480-66ab-11ea-91fa-22a6fbe36f3a.png)
![cp2](https://user-images.githubusercontent.com/56279630/76698426-71a06800-66ab-11ea-8685-9e53ec431d21.png)
![cp3](https://user-images.githubusercontent.com/56279630/76698427-7238fe80-66ab-11ea-9a64-b7d32a0b270b.png)

**Comment by ZamfirAndreiPaul** [comment]
For 2 days I keep changing and without result ... On the local it works just like commands in Linux..

**Comment by CraciunRAlexandra** [comment]
I also have the same problem, and not only me ..

**Comment by CraciunRAlexandra** [comment]
how can we solve it ??

**Comment by CraciunRAlexandra** [comment]
?

**Comment by ioanaculic** [comment]
I looked at both homeworks.

About the cat command, in both homework submissions, the write and read operations are not correctly implemented. The read needs to be done in a loop until you reach the end of file. As I already mentioned in another issue, the cat command is tested using the "nasty" module that you also had in lab 3. You can check if it works using that module, just like in the laboratory. We also recommend you look at the solutions for lab 3, where a correct implementation of write and read operations is available.

@ZamfirAndreiPaul  Regarding chmod, the permissions format varies based on the system, so the mistake here is that you manipulate the permission string by extracting the values at position 4,5 and 6. This is not correct for all architectures. However, you can change this by simply extracting the last 3 characters, as the last ones will always be the ones you need. The change needs to be done at lines 248-250.

@CraciunRAlexandra The chmod command is not completely implemented. I could not see any lines where the chmod command is completely parsed.

**Comment by ZamfirAndreiPaul** [comment]
Ok thanks , but I dont understand why my "cat" isn't good beacose reading until file is empty... I use a non-posix command?

**Comment by CraciunRAlexandra** [comment]
For me it wasn't a problem with chmod because it isn't done yet, only with ls and cat
Now I try to solve it. Thank you.

**Comment by ioanaculic** [comment]
You use a posix command, this is correct, but you do not use it correctly. 

Please check the solutions for lab 3, where a correct implementation of write is available.

**Comment by ZamfirAndreiPaul** [comment]
Ok, thanks.

**Comment by ZamfirAndreiPaul** [comment]
Another question. With cp command what is wrong?

**Comment by ZamfirAndreiPaul** [comment]
I modify this command 30times i think and doesn't work.

**Comment by ZamfirAndreiPaul** [comment]
And at chmod at ug + rw, the current mode must be changed. For example, if he has "661" and I call ug + x then his mode will be "771" or should everything be formatted? And be it only "110"?

**Comment by ZamfirAndreiPaul** [comment]
At this way I do take the 3 digits from the end and apply the operations depending on what they receive as a parameter, the local goes when I test and remove / add permissions but the checker does not ...

**Comment by ioanaculic** [comment]
The cp_simple_rename test, for instance, runs the following command: `python3 busybox.py cp /dev/nasty cp_file`. I tried running this with your homework and there is no cp_file being generated. This is why the test fails.

Again, please verify your read operations by using the nasty module from lab 3.

**Comment by ZamfirAndreiPaul** [comment]
How I can use this local?
