### ISSUE TITLE
Problems with ls

### ISSUE THREAD

**Issue by GeorgianaRaluca** [UPB-FILS/sde#23]
ls_all_r.sh checks for printing of '.' and '..', but ls_all.sh doesn't
Which is the right way to implement '-a'?

**Comment by ioanaculic** [comment]
You are right, this is a problem in the checker. The correct behaviour is to display '.' and '..' in both cases.

We have changed it in the checker. Please resubmit your homework.

**Comment by GeorgianaRaluca** [comment]
In which order should be printed, because ls from linux prints '.' and '..' first, but ls_all_r.sh prints '.' and '..' at the end?

**Comment by ioanaculic** [comment]
It does not matter, the checker ignores the order in which the files are printed.
