### ISSUE TITLE
Return doesn t work the program crash 

### ISSUE THREAD

**Issue by Mahdi-Abouledhenin** [UPB-FILS/sde#24]

**Comment by ioanaculic** [comment]
Please explain the exact issue you encounter.

**Comment by ahmed756** [comment]
when i try something that i m sure it has to return -20 or anything else the program dont execute i have to push ctrl+z to enter another command

**Comment by ioanaculic** [comment]
This is a problem in your program, which gets stuck, not from the checker. You need to figure this out.
