### ISSUE TITLE
Test bash command won't run on touch_simple_exists.sh

### ISSUE THREAD

**Issue by SchiopuMatei** [UPB-FILS/sde#25]
ls: cannot access 'my_super_file': No such file or directory

The file might have been deleted.

**Comment by GeorgianaRaluca** [comment]
I have a similar problem, but with touch_no_creat_new.sh.
The checker deletes the file and command touch -c my_super_file  won't create it again, then ls from the checker on it fails.

**Comment by ioanaculic** [comment]
There was a problem with test touch_simple_exists.sh. Not it is fixed and you both get the points for it.
