### ISSUE TITLE
SdE - Tema 4

### ISSUE THREAD

**Issue by DianaM1407** [UPB-FILS/sde#25]
In tema, se spune ca fisierele de intrare pentru fiecare proces au extensia .pse si ca ele contin doar instructiuni de tip p, s, f si exit; de fapt, fisierele .pse din verif contin cu totul si cu totul altceva, de exemplu (2-process.pse):
Start process 0
Start process 1
Running process 1
Syscall process 1, syscall number 3
End process 1

**Comment by alexandruradovici** [comment]
Acesta sunt fisierele pse, https://github.com/UPB-FILS/sde/tree/master/tema4/process, sunt corecte.
