### ISSUE TITLE
cp_r_file.sh test issues

### ISSUE THREAD

**Issue by SchiopuMatei** [UPB-FILS/sde#26]
I've used os.popen (only for testing purposes, this will not remain so), sending the command cp and it's arguments, emulating the exact bash behaviour of the command,  and the cp_r_file.sh test still fails.

Verifying cp_error_dir.sh................................ok (10p)
Verifying cp_error_file.sh................................ok (5p)
Verifying cp_rename_dir.sh...............................ok (20p)
Verifying cp_r_file.sh.................................error (0p)
Destination file does not exist.
Verifying cp_r.sh........................................ok (15p)
Verifying cp_simple_file.sh..............................ok (10p)
Verifying cp_simple_rename.sh............................ok (10p)

**Comment by ioanaculic** [comment]
The classical bash cp command preserves file types and attributes, while yours does not. This is why you cannot test the command using cp.

The checker simply verifies that the file you need to copy exists and has the same contents as the original one.

For this specific test, the file needs to be placed in a directory. Just to make sure that everything works fine, I also changed something to the tests. Please try to resubmit the homework.

**Comment by SchiopuMatei** [comment]
Thank you. One more question, are we allowed to use open() or must we use only os.open()?

**Comment by ioanaculic** [comment]
No, you can only use os.open()
