### ISSUE TITLE
Sd- Tema 4 - 1

### ISSUE THREAD

**Issue by DianaM1407** [UPB-FILS/sde#26]
Nu se spune absolut nimic in tema despre iesirea simulatorului ; din exemplele din verif se deduce ca el trebuie sa scrie in fisiere cu aceleasi nume ca cele de intrare, dar, dupa extensia .pse, cu extensiile suplimentare .alg.ref (unde alg este rr, rrp sau cfs, in functie de algoritmul utilizat): este corect?

**Comment by alexandruradovici** [comment]
Simulatorul este scris de noi si este integrat in sablonul de tema. Voi trebuie sa scrieti in main.c (si alte fisiere daca aveti nevoie).
