### ISSUE TITLE
SdE - Tema 4 - 3

### ISSUE THREAD

**Issue by DianaM1407** [UPB-FILS/sde#28]
De ce, de exemplu, pentru un fișier de intrare vid (e.g. 1-empty.pse), simulatorul trebuie sa genereze la iesire ceva, ca de exemplu, in 1-empty.pse.cfs.ref:
Start process 0
Start process 1
Running process 1
Syscall process 1, syscall number 3
End process 1
?

**Comment by alexandruradovici** [comment]
Uita-te in main.c, se genereaza procesul cu PID-ul 0 si procesul cu PID-ul 1, procesul care e gol.
