### ISSUE TITLE
Homework 1 Taks 07 Question

### ISSUE THREAD

**Issue by gramai** [UPB-FILS/sde#3]
I keep getting the error "Fisierul intermediar boo.o nu este creat" (The intermediary file boo.o is not created). Am I missing something?

**Comment by serban-razvan** [comment]
Hello

You are talking about the last part of the Task 7 am I right? There it says to create the intermediate files (files with .o and .s extension) based on the boo.c file.

I would look into the manual of "gcc" command : "man gcc" for a starting point

**Comment by gramai** [comment]
I have previously looked in the manual of the "gcc" command and have followed the instructions. The intermediary files (boo.o and boo.i) and boo.s have been created. Nonetheless, I am still getting "Fisierul intermediar boo.o nu este creat" when using "sudo uso check".

**Comment by xproxidizzy** [comment]
Me and 2 other friends have the same problem

**Comment by diana-ghindaoanu** [comment]
Same problem, and I looked too in the manual...

**Comment by alexandruradovici** [comment]
The checker is fixed, please run:

````bash
sudo uso update
````

There is another change at Task 7 described here https://ocw.cs.pub.ro/courses/sde/teme/tema_fr_1?do=diff&rev2%5B0%5D=1550477087&rev2%5B1%5D=&difftype=sidebyside.

**Comment by gramai** [comment]
The update fixed the problem for me. Thanks!
