### ISSUE TITLE
[busybox] From 3.6 to 0

### ISSUE THREAD

**Issue by Crastem13** [UPB-FILS/sde#30]
[Badea Ionut Teodor]
I already spent more than 5 days on this homework. Maybe i am dumb but i do not understand why i got from 3.6 on checker to 0. I tried to put an older version of the file and i still got 0. I am at the point of a breakdown. Please tell me what i did wrong.

**Comment by ioanaculic** [comment]
The file you upload needs to be named busybox.py. Any other file will not be tested.
