### ISSUE TITLE
difference between cat and busybox cat is null on self-made test files, 0 points

### ISSUE THREAD

**Issue by SchiopuMatei** [UPB-FILS/sde#31]
Multiple file cat and simple cat shows no difference when checked with bash cat.
Is the test ok? Could we get access to the nasty file to test it out?

**Comment by ioanaculic** [comment]
The nasty file is available in the repository for lab 3. The last exercise explains how to use the module.

Your homework works fine for the nasty file, it's just that it does not print correctly when multiple files are passed as parameter.
