### ISSUE TITLE
CP issue

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/sde#32]
I remake my CP command using lab3 for reading and writing in new file and dosen't work... With local testing working very well but on checker no...

**Comment by ioanaculic** [comment]
The /dev/nasty file is a special file and the isfile() function does not return true (line 197). You can resume to checking if the parameter is a directory and if not, assume it is a file.

**Comment by ZamfirAndreiPaul** [comment]
In my command it checks if the file is moved under a new name and if it is not renamed.

**Comment by ZamfirAndreiPaul** [comment]
I use lab3 for "cat" and work . And use cat for "cp" on locak its works but on checker no.

**Comment by ioanaculic** [comment]
Again, the cp does not work due to the isfile() function that you use in line 197. If you test that function for /dev/nasty, you will see that it does not return True.
However, you can assume that if isdir() returns False, the argument is a file, so you don't have to call the isfile() function.

**Comment by ZamfirAndreiPaul** [comment]
Verifying ls_file.sh...................................error (0p)
ls does not print file passed as parameter

My ls file display correct i think...

**Comment by ioanaculic** [comment]
It does not print correct. The output needs to be the same to any simple ls command you would run in a linux terminal.

**Comment by ZamfirAndreiPaul** [comment]
**Verifying rm_cascade.sh................................error (0p)
File/folder to be deleted exists.**

What is this?

**Comment by ioanaculic** [comment]
This means that not all files are removed when running rm.
