### ISSUE TITLE
-rm error 

### ISSUE THREAD

**Issue by Mariaoana** [UPB-FILS/sde#33]
Hello! At command ,,-rm" I obtained the error message ,,file folder to be deleted exists" and I don't understand why because it should exist.

**Comment by ioanaculic** [comment]
Please specify the test where the problem is.

This error message states that the folder should have been deleted but was not.

**Comment by Mariaoana** [comment]
All the tests from ,,-rm" return the same error : ,,file/folder to be deleted exists"

**Comment by ioanaculic** [comment]
I locally tested your homework for rm_simple and it does not work, the file supposed to be deleted is not. As mentioned before, this error message specifies you that the file is not deleted although it should have been.
