### ISSUE TITLE
Lab4 - Ex6 Issue

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/sde#37]
The error is at ex 6 of lab 4. At the last point of the exercise when I give the verification command gives me this (the image below). I would like to mention that depending on I have only os.open and os.dup2. I think it's an error in the initial code because the error says it needs an integer. My FD works because it creates my "out" file. File descriptor "filedes" is the problem I think, has no int value.

![errorlb4](https://user-images.githubusercontent.com/56279630/76862232-778e7880-6866-11ea-8e7c-1dea6b3e0e46.png)

**Comment by CraciunRAlexandra** [comment]
![55bd9135db994d82c0e9b26ae7858a8a](https://user-images.githubusercontent.com/56547343/76866643-15854180-686d-11ea-820b-3a2f826a91fd.png)

**Comment by ioanaculic** [comment]
Indeed, the file has an error on line 117.
I have just posted the solutions for tp04, where you can find the correct tiny.py file.

**Comment by ZamfirAndreiPaul** [comment]
Ok thanks
