### ISSUE TITLE
Question about how should work mini -shell?

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#39]
Hello ,Homework  said that the mini-shell must continue to operate when entering the cd command without a parameter.that  is not necessary to implement the behavior in bash (changing the current directory with the home directory of the current user) and no exit value for this scenario .Any suggestions about how can i do to make things in such a way that when i'm typing the command it  will not lead to error? Is it strictly related to the way I write errors?

**Comment by ioanaculic** [comment]
Hello,
Sorry, but I do not understand your question. Can you be more specific about the problem that you encounter?

**Comment by dragossolca** [comment]
Maybe you should google the pass statement to see what it does.

**Comment by dragossolca** [comment]
It is possible to understand easier if you check what the statement "pass" does. Hope that helps.
