### ISSUE TITLE
HW1 Login in the VM

### ISSUE THREAD

**Issue by alfredrogoveanu** [UPB-FILS/sde#4]
When the VirtualMachine demanded me the user and password and I typed my Moodle credentials instead of _student_, are they stocked as well in the VM...? Or did I screw something in the log-in...?

I am attaching a snapshot in order to understand better this situation. Thank you.

https://imgur.com/a/K54DrsB

**Comment by alexandruradovici** [comment]
Your credentials are fine, they did not get stored.

Alexandru
