### ISSUE TITLE
Checker issues.

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/sde#42]
Hello. Today I made the redirects, and I tested them by hand. Here is the result of the append. And the append err is fine.
![01e37a6a500b790cfcc152b435afcff0](https://user-images.githubusercontent.com/56279630/77824980-1476ce80-710f-11ea-9c1b-c7a15cff78ba.png)

The checker gives me error both at append out and at append err. I initially thought I didn't understand the functionality of append redirection ... so I tested it in the console.

![9725dee172bd6fc02354ac44b3a803b2](https://user-images.githubusercontent.com/56279630/77825002-35d7ba80-710f-11ea-9950-a36b73093cb8.png)

I have already modified the program 3 times without success. I do not know what the problem might be as long as he behaves like the bash.

**Comment by ioanaculic** [comment]
Could you please upload the homework on the vmchecker so I can look into the problem?

**Comment by ZamfirAndreiPaul** [comment]
I put the homework on the checker.

**Comment by ioanaculic** [comment]
The problem is that you don't create a new test.out file when using simple redirect. Try running the same commands when you already have a test.out file that contains some text and you should spot the problem.

**Comment by ZamfirAndreiPaul** [comment]
Ok I find the problem. Thanks.
