### ISSUE TITLE
Question regarding a TODO in cmd.py

### ISSUE THREAD

**Issue by dragossolca** [UPB-FILS/sde#43]
Hello! In the function run_simple_command I don't quite understand the first two TODOs. 

What does it mean to extract the command and the arguments?( I assume it means assigning a new variable its contents.)

Also how can I extract the redirects from the father command(I don't see what they are exactly). 

Furthermore, how can I see if a command is simple or not(I assume it is with using the isinstance of the SimpleCommand class but I don't quite get the grasp of it)
Can you give me some advice, please?

**Comment by ioanaculic** [comment]
I suggest you run parse_dump for several commands, including redirects. This way you can understand how the returned structure looks like and how you should manipulate it.

**Comment by dragossolca** [comment]
I see now. Thank you
