### ISSUE TITLE
Test for simple commands fails because it displays more dollars than it should

### ISSUE THREAD

**Issue by dragossolca** [UPB-FILS/sde#44]
<img width="683" alt="1" src="https://user-images.githubusercontent.com/56224261/77848871-7cd9b480-71d0-11ea-9469-a60510ede5d8.png">
<img width="767" alt="2" src="https://user-images.githubusercontent.com/56224261/77848873-7e0ae180-71d0-11ea-8c1f-30870ceadb23.png">

Can you give me a hint to solve this please?

**Comment by ioanaculic** [comment]
Can you please upload the homework on vmchecker so I can look into it?

**Comment by dragossolca** [comment]
I just did. Thank you

**Comment by ioanaculic** [comment]
First of all, make sure to include all .py files in you archive (parse.py and cmd.py and others if the case) when uploading the homework on vmchecker.

Regarding your problem, you call fork() without the need to do it, this is why your shell does not exit when exit or quit is written. Similarly to the exercise you had in TP4 (exercise 6), for internal commands (exit, quit, cd), you need to implement those, not create child processes.

**Comment by dragossolca** [comment]
Oh, I see why now. I have to call them in the parent process. Thank you
