### ISSUE TITLE
Good morning! I have a question about the files from git for devoir 3

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#45]
I tested the files on git from devoir 3, it does not show me anything, some I could only run with chmod +. After all, how should we orient ourselves, if they do not give us any output in the terminal, should we read them line by line with that parser? Is this what our mini-shell needs to do? Thanks a lot!

**Comment by ioanaculic** [comment]
Yes, your mini-shell needs to execute the commands in the test files.
