### ISSUE TITLE
homework1

### ISSUE THREAD

**Issue by Bassem-bk-1220** [UPB-FILS/sde#5]
hello, i make mistakes that i delet the folder devoir and tp from the folder sde .it's possible to return or any solution ???

**Comment by alexandruradovici** [comment]
Just clone the repository again.

**Comment by Bassem-bk-1220** [comment]
when make clone again they told me that the folder sde exists and is not empty and the problem that the folder devoir and tp is not exists

**Comment by Bassem-bk-1220** [comment]
> Just clone the repository again.

when make clone again they told me that the folder sde exists and is not empty and the problem that the folder devoir and tp is not exists .it's possible to repeat the homework from the begining

**Comment by alexandruradovici** [comment]
Delete the sde folder first
