### ISSUE TITLE
Helle,I have a question about homework 3

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#50]
Hello, I started writing the commands for the theme because I understood that the minishell must read line by line from the file! It gives me the parenting process and the pid, but I can not do the redirection,and also i have no help becouse it doesn't  tell me at which line I have the er
![20200331_164031 1](https://user-images.githubusercontent.com/56094498/78034106-efcd6180-736f-11ea-8335-2bfee848b312.jpg)
ror!

**Comment by dragossolca** [comment]
The parse.py already reads line by line for you. 

It is up to you to see what the parser gives you as output(parse_dump line in the cmd.py file).

Try some commands to see what it gives you as output like this:

python cmd.py
$some_command( e.g. ls -l)
