### ISSUE TITLE
About cd command homework 3 Sde

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#51]
Hello, related to cd command, which has to go without parameter, I searched and i can do with os and chdir, but it does not run without parameter, can you propose another solution?

**Comment by dragossolca** [comment]
Sure. For when you have a parameter you do as you said. 

If you have no parameter, it would be helpful to see what the "pass" statement does. You have some examples in the cmd.py file.

Hope that helps!

**Comment by alexandruradovici** [comment]
cd without any parameters go to the home directory, the HOME environment variable store the user’s home

**Comment by AlexandruCristian2312** [comment]
> Sure. For when you have a parameter you do as you said.
> 
> If you have no parameter, it would be helpful to see what the "pass" statement does. You have some examples in the cmd.py file.
> 
> Hope that helps!

It helped a lot ,thanks Dragos!

**Comment by AlexandruCristian2312** [comment]
I get it now ,thank you,Alex!
