### ISSUE TITLE
Error installing bashlex

### ISSUE THREAD

**Issue by andreiwf10** [UPB-FILS/sde#53]
Hi, an error occurs when I'm trying to install bashlex and I didn't find anything that works on web.
![error1](https://user-images.githubusercontent.com/59822876/78245087-7bb9c780-74ef-11ea-9010-ca4d624e6c2e.png)

**Comment by ioanaculic** [comment]
Sorry, there was a problem in the homework text. The correct command is: pip3 install bashlex --target=.

**Comment by andreiwf10** [comment]
Thank you.

**Comment by andreiwf10** [comment]
The error persists, I even tried another Linux distribution and it's the same story.

**Comment by andreiwf10** [comment]
It's working now, thanks
