### ISSUE TITLE
Process Issue

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/sde#56]
When I try to test the process test, the following sequence is printed on my screen.

![4c58acf3bda9f79389d0a67a296894c4](https://user-images.githubusercontent.com/56279630/78460597-c479a800-76ca-11ea-8456-fbfe7359658f.png)

The problem seems to be Parser because I have no print in the program.
I do not pass the local tester because of this print.

Should it be from Parser should I change it?

I tested the command without completing any code in the program and it prints the same thing on the screen.

**Comment by alexandruradovici** [comment]
Please update your repository and check that print cmd.py.

**Comment by ioanaculic** [comment]
There was an extra print line in parse.py. Now it should work.

**Comment by ZamfirAndreiPaul** [comment]
Ok , thanks.
