### ISSUE TITLE
Devoir 2

### ISSUE THREAD

**Issue by MohamedKonate** [UPB-FILS/sde#6]
Bonjour, 
Il y’a une erreur dans la partie « Commandes acceptées »
![548BA552-2D3F-48CE-8D84-09589580F2FF](https://user-images.githubusercontent.com/61732244/75759610-8b9e8a00-5d3e-11ea-8f58-6e018fc9fdd6.jpeg)

**Comment by ioanaculic** [comment]
Hello, sorry for the mistake. It is fixed now.
