### ISSUE TITLE
HI ,FOR HOMEWORK 3 ,TWO QUESTIONS 1) Errors EOF @) DOUBLE PROCESSES??

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#62]
1) i want to use this ,but do not work I want to write the error with try catch , no loop ,i think it's wrong in cmd , but it does not exist for EOF exception , please suggest me something...

2)Also ,we never ever did something like making two processes in the same time in the lab ,so please tell me how to build a process with two  with 2 children, one of which to read and the other to write, desperately, so please explain this test to me
 The test is wrong ,please change it ...
![test pipe double , three processes j eg](https://user-images.githubusercontent.com/56094498/78506534-cd2db500-7782-11ea-8e66-9c2574be3a5a.PNG)

**Comment by ioanaculic** [comment]
The test is not wrong. You also had to do this in your lab. You can check the extra TP, where you have an example of how to do this: https://web.microsoftstream.com/video/e824848a-c84c-4302-939b-c160f90d1bab

**Comment by AlexandruCristian2312** [comment]
I've already seen the extra TP, i was there , it isn't something generic like there ... It doesn't help , can you provide a solution ?Please explain me what i have to do ,the program has to take command commands.command , but in cmd.py it isn't specified what cmd ( cmd 1 or cmd 2 ) ,what commands has?

**Comment by ioanaculic** [comment]
You need to iterate the structure generated by parse.py and for each simple command in the structure you need to create a new process. For each two processes you need to create one pipe.
