### ISSUE TITLE
Priority Round Robin issue

### ISSUE THREAD

**Issue by DianaScurtu** [UPB-FILS/sde#65]
Hi, I have a question about the Priority Round Robin algorithm. For the 1-three-workers.pse test, why does a preempted process follow the same process again, even though it has lower priority than the others already in the queue?

<img width="552" alt="Captură de ecran din 2020-04-23 la 11 57 13" src="https://user-images.githubusercontent.com/46371782/80080275-0ffcd480-855a-11ea-9225-db977ef8fbe2.png">

**Comment by DianaScurtu** [comment]
The problem is with the priority of the process after it is preempted. 
Should it decrease or increase?

<img width="385" alt="Captură de ecran din 2020-04-23 la 13 36 46" src="https://user-images.githubusercontent.com/46371782/80090299-f5315c80-8567-11ea-9d37-884dc10964ea.png">

**Comment by alexandruradovici** [comment]
I think the priority rule might be a little confusing. We thought like
this: if the process is preempted, and still have units to process from the
current instruction, its priority is lowered. If it just finished the
instruction, this means he behaves nice and its priority is lifted. In your
case, I think you lower the priority anytime it is preempted, regardless of
whether it still has instructions to process.
