### ISSUE TITLE
Devoir 4

### ISSUE THREAD

**Issue by alexandra2607** [UPB-FILS/sde#67]
Hi, I have some questions from the code on the topic. SCHEDULER_PID is the current process pid? run function, I don't understand what it returns I read in the topic that it tells me if the process is preemted or syscall. I tried to do process.run (quantum) == PROCESS_PEEMPTED to check if it was executed properly I have to put it at the end of the queue for round robin. And function _run I tried to use it to check if it still has units to find out if the execution process is finished.
And I don't understand if process = Process (pid, first_process) is the process  with I have to work in 'while' and where I have to use it on scheduler = Process (0, '')?

**Comment by ioanaculic** [comment]
1. SCHEDULER_PID is the PID of the "empty process", also called scheduler. The one described here: https://ocw.cs.pub.ro/courses/sde/teme/tema_ro_4_python#procesul_scheduler.
2. The run function "runs" the process for the specified quantum and indeed returns PROCESS_PREEMPTED or PROCESS_SYSCALL. It is correct to run process.run (quantum) == PROCESS_PEEMPTED to check if it was executed properly.
3. You should not use the _run function in main.py. All functions beginning with _ are internal functions and should be used only inside process.py. To find out if it still needs to run, you should check the "units" property. If that is 0, the process finished execution.
4. process = Process (pid, first_process) is the first process you create from the file you read. Indeed, that is the one you will add to the list of processes and run. If that process will make a fork syscall, you will create other processes by running p = Process (pid, process.extra), where you need to compute the pid and process.extra is the parent process field.
5. The scheduler process is the "empty" process and you can use it when all the other processes called sleep you need to fill in empty quantums.

**Comment by alexandra2607** [comment]
Why  status = process.run () has no parameter?

**Comment by ioanaculic** [comment]
It should have the quantum as parameter, but you need to compute it.
