### ISSUE TITLE
Scheduler issue

### ISSUE THREAD

**Issue by cristinagavanescu** [UPB-FILS/sde#68]
Hello, I have a question regarging the process_sleep test: if a process sleep 1 sec, that means that there is appearing process with pid 0, which have p 1 and s 1, so that means 2 intervals of time, one for process call and one for sleep call, but the process which sleep needs just a second being sleeping.. and i can't see how can i manage this, if you could give me a hint..

**Comment by alexandruradovici** [comment]
Please take a quick look at this https://ocw.cs.pub.ro/courses/sde/teme/tema_fr_4#classe_process.

When a process asks you to sleep, lets say ``s 5``, it wants to sleep for at least 5 units. You have to add the process to a sleep queue and schedule another process. If there is no process that can be scheduled, you will schedule process 0, the one created in main. It does not matter what it executes, that is the simulator's job.

Each time `process.run(quantum)` returns, the process properties are modified:
  - `process.units` represents how many units it has left from the quantum. The amount of units that it has executed is `quantum - process.units`. This is the amount that you have to subtract from the `process.sleep` property of every process in the sleep queue. After subtracting, the processes that have a sleep property less or equal to 0, will be added to the ready queue.
  - `process.sleep` represents the number of units it wants to sleep. This should be modified after each run (by you) to represent how many units the process still needs to sleep

**Comment by cristinagavanescu** [comment]
Can you please take a look on my code? I think that i have a different way of solving  things and i don t know if it s good

**Comment by alexandruradovici** [comment]
Please upload it to vmchecker.

**Comment by cristinagavanescu** [comment]
It's already there :)

**Comment by ioanaculic** [comment]
Overall it seems ok, but there is a problem with the scheduler process (pid = 0). That process should not be added to the process queue. You should add only the other processes and if at a certain point all processes are in sleep mode, then you automatically call run on the scheduler.

**Comment by cristinagavanescu** [comment]
I have put it in the queue because i have seen that in while condition, the length of the queue processes is required > 1, so, maybe i can modify there?  ( i have create a condition for not execute the scheduler when there are other processes in the queue)

**Comment by ioanaculic** [comment]
You can modify the number_processes function so you consider that you always have the scheduler process, without adding it to the list.

**Comment by ioanaculic** [comment]
The condition to not execute the scheduler when there are other processes in the queue is also a correct solution.

**Comment by cristinagavanescu** [comment]
Thank you!
