### ISSUE TITLE
[ Busy_Box ] Chmod Errors

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/sde#8]
## Chmod Errors in VmChecker

I think that my programs sets the permissions fine, but  VmChecker gives me errors

![Screenshot from 2020-03-06 15-15-47](https://user-images.githubusercontent.com/61273664/76088466-cb74a400-5fc0-11ea-8f76-88714a3e4f1b.png)

Thank you in advance for solutions :+1:

**Comment by ioanaculic** [comment]
Hello,

We changed the chmod tests on the checker. Please resubmit the homework.

**Comment by RaduNicolaeEduard** [comment]
Still does not work, I think i have a bug for chmod_del_multiple.sh and chmod_del_one.sh
but for the other checks it should work

**Comment by RaduNicolaeEduard** [comment]
If the command is  g+x  to set the group to executable,
My program sets the group to executable , and the user and other to no permissions, is it supposed to not change the other permissions?

**Comment by RaduNicolaeEduard** [comment]
I think i got, it i am supposed to only add the r/w/x part to the permissions, not to set the user permissions to r/w/x
